-- 상품 서비스 기존 스키마 베이스라인.
--
-- Flyway 도입 전까지는 spring.jpa.hibernate.ddl-auto: update로 스키마를 관리해왔다.
-- 이 파일은 그렇게 이미 만들어져 있는 스키마를 그대로 옮겨 적은 것이다.
--   - 스키마가 이미 있는 환경(local 등): spring.flyway.baseline-on-migrate=true라서
--     이 파일은 실행되지 않고 버전 1로 베이스라인만 기록된다.
--   - 스키마가 비어 있는 환경(신규 DB): 이 파일이 그대로 실행되어 스키마를 만든다.
-- 그래서 아래 DDL은 각 엔티티의 현재 @Column/@JoinColumn 매핑과 정확히 일치해야 한다.
-- 어긋나면 ddl-auto: validate 전환 후 애플리케이션이 기동하지 못한다.

CREATE TABLE category
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name      VARCHAR(225) NOT NULL,
    type      VARCHAR(20),
    sequence  INTEGER
);

CREATE TABLE product
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_code          VARCHAR(50),
    parent_id         BIGINT,
    name              VARCHAR(225) NOT NULL,
    short_description VARCHAR(225),
    brand             VARCHAR(100),
    price             BIGINT       NOT NULL,
    discount_rate     INTEGER,
    sale_price        BIGINT,
    type              VARCHAR(10),
    status            VARCHAR(10),
    like_count        INTEGER,
    total_sales_count BIGINT,
    created_at        TIMESTAMP(6)
);

CREATE TABLE category_media
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT       NOT NULL REFERENCES category (id),
    media_url   VARCHAR(512) NOT NULL,
    s3_key      VARCHAR(255)
);

CREATE TABLE product_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT  NOT NULL REFERENCES product (id),
    category_id BIGINT  NOT NULL REFERENCES category (id),
    is_main     BOOLEAN NOT NULL
);

CREATE TABLE product_media
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES product (id),
    media_url  VARCHAR(512) NOT NULL,
    s3_key     VARCHAR(255),
    media_type VARCHAR(10),
    media_role VARCHAR(20),
    sequence   INTEGER
);

CREATE TABLE product_spec
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT NOT NULL UNIQUE REFERENCES product (id),
    storage_type   VARCHAR(20),
    packaging_type VARCHAR(20),
    attributes     TEXT
);

CREATE TABLE product_inventory
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT  NOT NULL UNIQUE REFERENCES product (id),
    base_quantity     INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL,
    updated_at        TIMESTAMP(6)
);
