-- 상품 서비스 아웃박스 테이블.
--
-- 재고 확정/복구 처리와 같은 트랜잭션에서 결과 이벤트를 적재한다(ProductInventoryService).
-- 실제 브로커 발행은 이 테이블을 폴링하는 별도 워커가 맡는다(이후 단계에서 추가 예정).

CREATE TABLE product_outbox
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     VARCHAR(36)  NOT NULL UNIQUE,
    exchange     VARCHAR(100) NOT NULL,
    routing_key  VARCHAR(200) NOT NULL,
    type_id      VARCHAR(300) NOT NULL,
    payload      TEXT         NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    published_at TIMESTAMP(6),
    CONSTRAINT chk_product_outbox_status CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

-- 발행 워커가 미발행 건을 오래된 순으로 훑는 조회 경로.
CREATE INDEX idx_product_outbox_status_created_at ON product_outbox (status, created_at);
