-- 인박스(멱등성 마커) 테이블.
--
-- WMS 등 외부 서비스가 발행한 이벤트(입고/출고 완료 등)를 처리하기 전, 같은 트랜잭션 안에서
-- event_id를 먼저 적재해 브로커 재전달로 인한 중복 처리(재고 이중 반영)를 막는다.

CREATE TABLE product_consumed_event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(36)  NOT NULL UNIQUE,
    event_type  VARCHAR(50)  NOT NULL,
    consumed_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_product_consumed_event_type CHECK (event_type IN ('INBOUND_COMPLETED', 'OUTBOUND_COMPLETED'))
);
