CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 상품 목록/필터 검색의 keyword가 name과 brand 어디에 있든(substring) 매칭하도록
-- concat(name, ' ', brand) 표현식을 쓰므로, 그 표현식과 정확히 일치하는 함수 기반 GIN 인덱스를
-- 만든다. Hibernate가 실제로 내보내는 SQL 표현식(name||' '||coalesce(brand,''))과 문자 그대로
-- 일치해야 planner가 이 인덱스를 탄다.
CREATE INDEX idx_product_search_trgm ON product USING GIN ((name || ' ' || coalesce(brand, '')) gin_trgm_ops);

-- 자동완성용 정제 키워드 사전. 상품명 원문 대신 이 테이블의 키워드를 색인해
-- "전용목장우유 900mL"/"전용목장우유 1.8L"처럼 용량만 다른 상품이 중복 제안되는 것을 피하고,
-- 브랜드명도 자동완성 대상에 포함한다. 시드 데이터는 db/seed/seed_product_service.sql 참고.
CREATE TABLE search_keyword
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL UNIQUE
);
