-- 출고 피킹 전용 작업 지시. 보관존→피킹존 보충은 이미 StockMovement가 자체 상태(PENDING/
-- IN_PROGRESS/COMPLETED/CANCELED)와 확정 API를 갖고 있어 Task로 따로 감싸지 않는다 — 감싸면
-- StockMovement.status와 Task.status 두 곳이 서로 어긋날 여지가 생긴다. Task는 오직 피킹만
-- 다루므로 outbound_order_id/outbound_item_id는 항상 채워진다(NOT NULL).
CREATE TABLE task
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no            VARCHAR(64) NOT NULL,
    status             VARCHAR(30) NOT NULL,
    warehouse_id       BIGINT      NOT NULL REFERENCES warehouse (id),
    outbound_order_id  BIGINT      NOT NULL REFERENCES outbound_order (id),
    outbound_item_id   BIGINT      NOT NULL REFERENCES outbound_item (id),
    worker_id          BIGINT,
    started_at         TIMESTAMP(6),
    completed_at       TIMESTAMP(6),
    created_at         TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP(6) NOT NULL DEFAULT now(),
    CONSTRAINT uk_task_task_no UNIQUE (task_no),
    -- 품목 하나에 피킹 Task가 중복 생성되는 걸 막는다(OutboundAllocatedEvent가 재배달돼도 안전).
    CONSTRAINT uk_task_outbound_item_id UNIQUE (outbound_item_id),
    CONSTRAINT chk_task_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELED'))
);

-- task_no 채번용 시퀀스. TSK-PICK-<yyyyMMdd>-<이 시퀀스 값> 형태로 조합한다 — 일자별로 1부터
-- 다시 시작하는 건 아니고 전역으로 계속 증가하는 값이라, 예시로 받은 번호 형식과 완전히 같지는
-- 않다(001, 002 ... 형태의 일자별 리셋 카운터를 구현하려면 별도 테이블/락이 더 필요해서 우선
-- 단순한 전역 시퀀스로 시작한다).
CREATE SEQUENCE task_no_seq;

CREATE INDEX idx_task_warehouse_id ON task (warehouse_id);
CREATE INDEX idx_task_outbound_order_id ON task (outbound_order_id);
CREATE INDEX idx_task_worker_id ON task (worker_id);
