-- WMS 서비스 베이스라인 스키마.
--
-- docs/erd-spec.md에 정의된 데이터 모델을 docs/CLAUDE.md 엔티티 컨벤션(JPA @Column/@JoinColumn 매핑)에
-- 맞춰 옮긴 것이다. product-service와 동일하게, 이 DDL은 각 엔티티의 매핑과 정확히 일치해야 한다.
-- 어긋나면 ddl-auto: validate 전환 시 애플리케이션이 기동하지 못한다.

CREATE TABLE warehouse
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code      VARCHAR(50)  NOT NULL UNIQUE,
    name      VARCHAR(255) NOT NULL,
    address   VARCHAR(255),
    is_active BOOLEAN      NOT NULL
);

-- id는 자체 채번하지 않고 상품 서비스의 Product UNIT ID를 그대로 사용한다(WmsProduct 엔티티 참고).
CREATE TABLE wms_product
(
    id              BIGINT PRIMARY KEY,
    sku_code        VARCHAR(50)  NOT NULL UNIQUE,
    barcode         VARCHAR(50),
    name            VARCHAR(255) NOT NULL,
    storage_type    VARCHAR(20)  NOT NULL,
    box_unit_qty    INTEGER      NOT NULL,
    pallet_box_qty  INTEGER      NOT NULL,
    safety_stock    INTEGER
);

CREATE TABLE location
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id  BIGINT      NOT NULL REFERENCES warehouse (id),
    location_type VARCHAR(20) NOT NULL,
    storage_type  VARCHAR(20) NOT NULL,
    zone          VARCHAR(20),
    aisle         VARCHAR(20) NOT NULL,
    rack          VARCHAR(20) NOT NULL,
    level         INTEGER     NOT NULL,
    bin           VARCHAR(20) NOT NULL,
    status        VARCHAR(20) NOT NULL,
    CONSTRAINT uk_location_address UNIQUE (warehouse_id, aisle, rack, level, bin)
);

CREATE TABLE inbound_order
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id   BIGINT      NOT NULL REFERENCES warehouse (id),
    supplier_name  VARCHAR(255),
    status         VARCHAR(20) NOT NULL,
    expected_date  TIMESTAMP(6),
    completed_date TIMESTAMP(6)
);

CREATE TABLE inbound_item
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbound_order_id     BIGINT      NOT NULL REFERENCES inbound_order (id),
    product_id           BIGINT      NOT NULL REFERENCES wms_product (id),
    inbound_unit         VARCHAR(20) NOT NULL,
    ordered_quantity     INTEGER     NOT NULL,
    inspect_quantity     INTEGER,
    total_base_quantity  INTEGER,
    lpn_code             VARCHAR(50),
    lot_no               VARCHAR(50),
    expired_date         DATE,
    target_location_id   BIGINT REFERENCES location (id),
    status               VARCHAR(20) NOT NULL
);

CREATE TABLE inventory
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id      BIGINT  NOT NULL REFERENCES warehouse (id),
    location_id       BIGINT  NOT NULL REFERENCES location (id),
    product_id        BIGINT  NOT NULL REFERENCES wms_product (id),
    lpn_code          VARCHAR(50),
    lot_no            VARCHAR(50),
    expired_date      DATE,
    quantity          INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL,
    updated_at        TIMESTAMP(6),
    CONSTRAINT uk_inventory_lot UNIQUE (warehouse_id, location_id, product_id, lot_no, expired_date, lpn_code),
    CONSTRAINT chk_inventory_quantity CHECK (quantity >= 0),
    CONSTRAINT chk_inventory_reserved_quantity CHECK (reserved_quantity >= 0)
);

CREATE TABLE stock_movement
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id      BIGINT      NOT NULL REFERENCES warehouse (id),
    product_id        BIGINT      NOT NULL REFERENCES wms_product (id),
    lpn_code          VARCHAR(50),
    lot_no            VARCHAR(50),
    expired_date      DATE,
    from_location_id  BIGINT REFERENCES location (id),
    to_location_id    BIGINT REFERENCES location (id),
    movement_unit     VARCHAR(20) NOT NULL,
    unit_quantity     INTEGER     NOT NULL,
    quantity          INTEGER     NOT NULL,
    movement_type     VARCHAR(20) NOT NULL,
    status            VARCHAR(20) NOT NULL,
    created_at        TIMESTAMP(6),
    completed_at      TIMESTAMP(6)
);

CREATE TABLE outbound_order
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT,
    warehouse_id BIGINT      NOT NULL REFERENCES warehouse (id),
    status       VARCHAR(20) NOT NULL,
    created_at   TIMESTAMP(6)
);

CREATE TABLE outbound_item
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbound_order_id  BIGINT      NOT NULL REFERENCES outbound_order (id),
    product_id         BIGINT      NOT NULL REFERENCES wms_product (id),
    lpn_code           VARCHAR(50),
    lot_no             VARCHAR(50),
    expired_date       DATE,
    location_id        BIGINT REFERENCES location (id),
    ordered_quantity   INTEGER     NOT NULL,
    picked_quantity    INTEGER     NOT NULL,
    status             VARCHAR(20) NOT NULL
);

-- Transactional Outbox. 실제 브로커 발행은 이 테이블을 폴링하는 별도 워커가 맡는다(이후 단계에서 추가 예정).
CREATE TABLE outbox
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(50)  NOT NULL,
    aggregate_id   VARCHAR(50)  NOT NULL,
    event_type     VARCHAR(100) NOT NULL,
    payload        JSONB        NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    created_at     TIMESTAMP(6),
    CONSTRAINT chk_outbox_status CHECK (status IN ('INIT', 'PUBLISHED'))
);

-- 발행 워커가 미발행 건을 오래된 순으로 훑는 조회 경로.
CREATE INDEX idx_outbox_status_created_at ON outbox (status, created_at);
