-- 기존 outbox 테이블(erd-spec.md의 범용 aggregate_type/aggregate_id/event_type 설계, Kafka
-- 전제)은 실제 발행자가 하나도 없었다. 이 저장소는 실제로는 RabbitMQ만 쓰고 있고
-- (common 모듈의 spring-boot-starter-amqp), product-service가 이미 검증한 발행용 스키마
-- (product_outbox: exchange/routing_key/type_id/published_at)가 있어 그대로 재사용한다.
DROP TABLE outbox;

CREATE TABLE wms_outbox
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     VARCHAR(36)  NOT NULL UNIQUE,
    exchange     VARCHAR(100) NOT NULL,
    routing_key  VARCHAR(200) NOT NULL,
    type_id      VARCHAR(300) NOT NULL,
    payload      TEXT         NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    published_at TIMESTAMP(6),
    CONSTRAINT chk_wms_outbox_status CHECK (status IN ('PENDING', 'PUBLISHED'))
);

-- 발행 워커가 미발행 건을 오래된 순으로 훑는 조회 경로.
CREATE INDEX idx_wms_outbox_status_created_at ON wms_outbox (status, created_at);
