spring:
  application:
    name: product-service
  profiles:
    default: local
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

server:
  port: 8084

kurly:
  security:
    enabled: true
