spring:
  application:
    name: order-service
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

services:
  oms:
    base-url: ${OMS_SERVICE_BASE_URL:http://localhost:8086}
  payment:
    base-url: ${PAYMENT_SERVICE_BASE_URL:http://localhost:8083}
  product:
    base-url: ${PRODUCT_SERVICE_BASE_URL:http://localhost:8084}
  member:
    base-url: ${MEMBER_SERVICE_BASE_URL:http://localhost:8088}
  http:
    connect-timeout: ${SERVICE_CONNECT_TIMEOUT:2s}
    read-timeout: ${SERVICE_READ_TIMEOUT:5s}
  storage:
    refund-attachment-bucket: ${REFUND_ATTACHMENT_BUCKET:refund-attachments}
