version: '3.8'

services:
  oms-postgres:
    image: postgres:17-alpine
    container_name: kurly-oms-postgres
    environment:
      POSTGRES_DB: oms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - oms_pgdata:/var/lib/postgresql/data

volumes:
  oms_pgdata: