name: CI - oms-service

on:
  push:
    branches: [develop]
    paths:
      - 'services/oms-service/**'
  pull_request:
    branches: [develop]
    paths:
      - 'services/oms-service/**'
  workflow_dispatch:

jobs: {}
