name: CI - user-service

on:
  push:
    branches: [develop]
    paths:
      - 'services/user-service/**'
  pull_request:
    branches: [develop]
    paths:
      - 'services/user-service/**'
  workflow_dispatch:

jobs: {}
